listening-port=3478
tls-listening-port=5349

realm=rtc.ktranowl.id.vn
server-name=rtc.ktranowl.id.vn

lt-cred-mech
user=testuser:testpassword

cert=/etc/letsencrypt/live/rtc.ktranowl.id.vn/fullchain.pem
pkey=/etc/letsencrypt/live/rtc.ktranowl.id.vn/privkey.pem

fingerprint
no-multicast-peers

listening-ip=172.31.36.240
relay-ip=172.31.36.240
external-ip=13.212.86.112/172.31.36.240

min-port=49152
max-port=65535

verbose